# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2d76f85c0e1f1f408a8246a89ca874489f52a828ca68cdd0b69387066f8c619b12af4816d03d0f3f28586893ceb8c6d50009cd895c89444143a7f209d52e73e

test:
  secret_key_base: 105218327476961dd6549bd328d97a72b23760f121aafa4a744e63d2b5c3db15ba7bb66ec1019e065a5ec4d8f816b59cd07619f740c42c5e13554b2def543851

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
